def application(environ, start_response):
    start_response('200 OK', [('Content-Type', 'text/html')])
    body = '<h1>Hello, %s!</h1>' % (environ['PATH_INFO'][1:] or 'web')
    result = {
             'USERPROFILE': 'C:\\Users\\zhang',
             'SYSTEMDRIVE': 'C:',
             'GATEWAY_INTERFACE': 'CGI/1.1',
             'PROGRAMDATA': 'C:\\ProgramData',
             'HOMEPATH': '\\Users\\zhang',
             'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
             'HTTP_HOST': 'localhost:8000',
             'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
             'PROGRAMFILES': 'C:\\Program Files',
             'REQUEST_METHOD': 'GET',
             'SERVER_NAME': 'zrx-win10pc',
             'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
             'HOMEDRIVE': 'C:',
             'REMOTE_ADDR': '127.0.0.1',
             'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
             'USERNAME': 'zhang',
             'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8',
             'VSSDK140INSTALL': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\',
             'NEXUS_HOME': 'D:\\ProgramDev\\nexus-2.8.1-01-bundle\\nexus-2.8.1-01',
             'wsgi.multithread': True,
             'SCRIPT_NAME': '',
             'HTTP_UPGRADE_INSECURE_REQUESTS': '1',
             'PYTHONIOENCODING': 'UTF-8',
             'PROCESSOR_ARCHITECTURE': 'AMD64',
             'wsgi.errors': '<_io.TextIOWrapper name=\'<stderr>\' mode=\'w\' encoding=\'UTF-8\'>',
             'LOGONSERVER': '\\\\ZRX-WIN10PC',
             'NUMBER_OF_PROCESSORS': '4',
             'PUBLIC': 'C:\\Users\\Public',
             'USERDOMAIN': 'ZRX-WIN10PC',
             'PROCESSOR_LEVEL': '6',
             'PYTHONUNBUFFERED': '1',
             'wsgi.multiprocess': False,
             'PYCHARM_HOSTED': '1',
             'MONGODB_HOME': 'D:\\ProgramDev\\MongoDB\\Server\\3.2\\',
             'NGROK': 'D:\\ProgramDev\\ngrok_2.0.19_windows_386',
             'TMP': 'C:\\Users\\zhang\\AppData\\Local\\Temp',
             'SERVER_PROTOCOL': 'HTTP/1.1',
             'HTTP_CACHE_CONTROL': 'max-age=0',
             'wsgi.url_scheme': 'http',
             'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW',
             'PROGRAMW6432': 'C:\\Program Files',
             'VIM_HOME': 'D:\\Program Files\\Vim\\vim74',
             'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
             'VS140COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
             'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
             'wsgi.version': (1, 0),
             'LOCALAPPDATA': 'C:\\Users\\zhang\\AppData\\Local',
             'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch, br',
             'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\;D:\\Program Files\\VisualSVN Server\\PowerShellModules',
             'HTTP_COOKIE': '9d4bb4a09f511681369671a08beff228=ugdmk3ueeebatq5ki6isuptms5; 0b2dc6a25897b6f975d6d9d43aab7918=3erjbhmq2cdtt73hjkn57i02t7; joomla_user_state=logged_in; 221820c38800abfed3cfe6d6b9cafaf8=7umpn3g2pd9pf1k5j4g0muii32; session_id_ip=127.0.0.1_107667ef3c8e01a8afa0ac7a36ad6fba; bdshare_firstime=1471944246502; pgv_pvi=6623936512; pgv_si=s685743104; ECSCP_ID=89486cb98a966d09732ea91d9f4c4e2de96fe2cd; ECS_ID=a2e7c26c5f21e1ce66182d6e3f34a72532a581a6; ECS[visit_times]=7; Hm_lvt_cdf78c4f7225eb2b21987d773d45fd21=1472612767; Hm_lpvt_cdf78c4f7225eb2b21987d773d45fd21=1472612898; Webstorm-96d8c47d=5c3d0547-e26e-4fdd-8c22-f9ee5e753f89; Phpstorm-34e0e9a1=8b94d9ac-f1f3-4a8b-98ec-7b07895cc1af; tocTree-hi=; tocTree_ref-topic-group:ref-group-standaloneinstances:ref-standaloneinstancesText-hi=tocTree:ref-topic-group:ref-group-standaloneinstances:ref-standaloneinstances:ref-standaloneinstances_link; treeForm_tree-hi=treeForm:tree:resources:JDBC:jdbcResources; android_developer_pref_lang=zh-cn; android_developer_api_level=24; __RequestVerificationToken=6nVzMRkSXukeO90f-RdQgdZksuG4M0rD3Kp_Ym1QKXQtu3P72hX9FFogONCcjo3dfUZJtYHMn5_ILGa-ZEzStUlhvaABztv2a-GvE1RWhVY1; Phpstorm-9cc21680=e6e7a4a1-be6b-46f2-810c-10c49630a639; PHPSESSID=6b8rllviv9h02nrnm35ipst30e; _identity=e7783d695e76428b8c1dcaf3aec1645053ead0199873e009443eb9f84c10283aa%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A28%3A%22%5B%22100%22%2C%22test100key%22%2C2592000%5D%22%3B%7D; _csrf=927583867f001442cb67575b12f2510b092e7497083fd773713395f0dc68b2eca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22nDRzHSqL1PV84kz9aXowT8szOT-6DGGB%22%3B%7D; ___rl__test__cookies=1482458766037; csrftoken=ZtpM4tuL5enGEMFvuVtTAAvRXGMGRCIbcHoexRgdZy1Hm5xpJbF9v70KubPcjs13; JSESSIONID=857E5EAF503888B9BC0AF8F3C48A9DF6',
             'QUERY_STRING': '',
             'CONTENT_TYPE': 'text/plain',
             'HTTP_CONNECTION': 'keep-alive',
             'WINDIR': 'C:\\WINDOWS',
             'ALLUSERSPROFILE': 'C:\\ProgramData',
             'SERVER_PORT': '8000',
             'JAVA_HOME': 'D:\\ProgramDev\\Java\\jdk1.8.0_60',
             'DOCKER_TOOLBOX_INSTALL_PATH': 'C:\\Program Files\\Docker Toolbox',
             'CONTENT_LENGTH': '',
             'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
             'OS': 'Windows_NT',
             'ADB_HOME': 'D:\\ProgramDev\\Android\\android-sdk-windows\\platform-tools',
             'APPDATA': 'C:\\Users\\zhang\\AppData\\Roaming',
             'REMOTE_HOST': '',
             'TEMP': 'C:\\Users\\zhang\\AppData\\Local\\Temp',
             'wsgi.input': '<_io.BufferedReader name=716>',
             'AWE_DIR': 'D:\\Program Files\\Khrona LLC\\Awesomium SDK\\1.6.6\\',
             'wsgi.file_wrapper': '<class \'wsgiref.util.FileWrapper\'>',
             'PATH_INFO': '/www',
             'VISUALSVN_SERVER': 'D:\\Program Files\\VisualSVN Server\\',
             'VBOX_MSI_INSTALL_PATH': 'D:\\ProgramDev\\Oracle\\VirtualBox\\',
             'SYSTEMROOT': 'C:\\WINDOWS',
             'SESSIONNAME': 'Console',
             'FAST': 'D:\\SOFT',
             'PYTHONPATH': 'E:\\PycharmProjects\\python3',
             'M3_HOME': 'D:\\ProgramDev\\apache-maven-3.3.3',
             'SERVER_SOFTWARE': 'WSGIServer/0.2',
             'PROCESSOR_REVISION': '3a09',
             'COMPUTERNAME': 'ZRX-WIN10PC',
             'USERDOMAIN_ROAMINGPROFILE': 'ZRX-WIN10PC',
             'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
             'PATH': 'D:\\ProgramDev\\Python\\Scripts\\;D:\\ProgramDev\\Python\\;C:\\Program Files (x86)\\Common Files\\NetSarang;D:\\ProgramDev\\OracleEx\\app\\oracle\\product\\11.2.0\\server\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\zhang\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;D:\\ProgramDev\\Java\\jdk1.8.0_60\\bin;D:\\ProgramDev\\Java\\jdk1.8.0_60\\jre\\bin;D:\\ProgramDev\\MySQL\\MySQL Server 5.5\\bin;D:\\ProgramDev\\scala\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\ProgramDev\\apache-maven-3.3.3\\bin;D:\\ProgramDev\\nexus-2.8.1-01-bundle\\nexus-2.8.1-01\\bin;D:\\SOFT;D:\\Program Files\\Vim\\vim74;D:\\ProgramDev\\Android\\android-sdk-windows\\platform-tools;D:\\Program Files\\TortoiseSVN\\bin;D:\\ProgramDev\\ngrok_2.0.19_windows_386;D:\\ProgramDev\\HashiCorp\\Vagrant\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;D:\\ProgramDev\\nodejs\\;D:\\Program Files\\VisualSVN Server\\bin;D:\\Wanp\\nginx-1.11.4;D:\\ProgramDev\\MongoDB\\Server\\3.2\\\\bin;D:\\ProgramDev\\Java\\jdk1.8.0_60\\bin;D:\\ProgramDev\\cygwin64\\bin;D:\\ProgramDev\\GnuWin32\\bin;D:\\Wanp\\php-7.1.0;C:\\ProgramData\\ComposerSetup\\bin;D:\\ProgramDev\\TortoiseGit\\bin;D:\\ProgramDev\\Git\\cmd;D:\\ProgramDev\\Python;C:\\Users\\zhang\\AppData\\Roaming\\npm;C:\\Users\\zhang\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\Docker Toolbox;C:\\Users\\zhang\\AppData\\Roaming\\Composer\\vendor\\bin',
             'CLASSPATH': '.;D:\\ProgramDev\\Java\\jdk1.8.0_60\\lib;D:\\ProgramDev\\Java\\jdk1.8.0_60\\lib\\tools.jar',
             'wsgi.run_once': False
    }
    print(environ)
    a = "<pre>"
    for k in environ:
        a = a + k +" : "+ str(environ[k]) +"<br>"
    a = a.join("<pre>")
    return [a.encode('utf-8')]

